---
abstract: 'Sync CPAN testers failure reports to local directories'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.70
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-sync_cpantesters
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Getopt::Attribute: 0
  HTML::FormatText: 0
  HTML::TreeBuilder: 0
  LWP::UserAgent::ProgressBar: 0
  Web::Scraper: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
