---
abstract: 'Sync CPAN testers failure reports to local directories'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  Carp: 0
  English: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-sync_cpantesters
provides:
  App::sync_cpantesters:
    file: lib/App/sync_cpantesters.pm
    version: 1.110730
requires:
  Cwd: 0
  File::Find: 0
  File::Path: 0
  File::Spec: 0
  Getopt::Attribute: 0
  HTML::FormatText: 0
  HTML::TreeBuilder: 0
  LWP::UserAgent::ProgressBar: 0
  Pod::Usage: 0
  Web::Scraper: 0
  open: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=App-sync_cpantesters
  homepage: http://search.cpan.org/dist/App-sync_cpantesters/
  repository: git://github.com/hanekomu/App-sync_cpantesters.git
version: 1.110730
