--- 
abstract: Sync CPAN testers failure reports to local dir
author: 
  - "{% ELSE %}"
build_requires: 
  Test::Compile: 0
  Test::More: 0
  UNIVERSAL::require: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: App-sync_cpantesters
no_index: 
  directory: 
    - inc
    - t
requires: 
  Getopt::Attribute: 0
  HTML::FormatText: 0
  HTML::TreeBuilder: 0
  LWP::Simple: 0
  URI: 0
  Web::Scraper: 0
  perl: 5.6.0
version: 0.03
